# language: generic

# sudo : required
# services:
#   - docker


# before_install:
#   - docker build -t iamthemayankkaushal/front-end -f Dockerfile.dev

# script:
#   - docker run -e CI=true iamthemayankkaushal/front-end npm run test  



